/* 
 * Copyright 2014 roylisto.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package GUI;

/**
 *
 * @author roylisto
 */

import Video.AerialVideo;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */        
    public MainForm() {
        initComponents();      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadionButtonGroup = new javax.swing.ButtonGroup();
        PanelTools = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnConvertToMjpeg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radioUseConverted = new javax.swing.JRadioButton();
        radioUseOriginal = new javax.swing.JRadioButton();
        checkBoxSameAsSource = new javax.swing.JCheckBox();
        BtnSetConvertedDir = new javax.swing.JButton();
        inputFileDir = new javax.swing.JTextField();
        inputConvertedDir = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaCommandOutput = new javax.swing.JTextArea();
        inputSetName = new javax.swing.JTextField();
        btnSetName = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputMapName = new javax.swing.JTextField();
        inputVideoName = new javax.swing.JTextField();
        BtnStartMosaicing = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuOpenFile = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UAV Sight System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PanelTools.setBorder(javax.swing.BorderFactory.createTitledBorder("Tools"));

        jLabel1.setText("File Dir");

        BtnConvertToMjpeg.setText("Convert To Mjpeg");
        BtnConvertToMjpeg.setEnabled(false);

        jLabel2.setText("Converted File Dir ");

        RadionButtonGroup.add(radioUseConverted);
        radioUseConverted.setText("Use Converted");
        radioUseConverted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUseConvertedActionPerformed(evt);
            }
        });

        RadionButtonGroup.add(radioUseOriginal);
        radioUseOriginal.setSelected(true);
        radioUseOriginal.setText("Use Original Source");
        radioUseOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUseOriginalActionPerformed(evt);
            }
        });

        checkBoxSameAsSource.setSelected(true);
        checkBoxSameAsSource.setText("Same As Source");
        checkBoxSameAsSource.setEnabled(false);
        checkBoxSameAsSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSameAsSourceActionPerformed(evt);
            }
        });

        BtnSetConvertedDir.setText("...");
        BtnSetConvertedDir.setEnabled(false);

        inputFileDir.setEditable(false);

        inputConvertedDir.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Command Output"));

        TextAreaCommandOutput.setBackground(new java.awt.Color(0, 0, 0));
        TextAreaCommandOutput.setColumns(20);
        TextAreaCommandOutput.setForeground(new java.awt.Color(0, 255, 0));
        TextAreaCommandOutput.setRows(3);
        jScrollPane1.setViewportView(TextAreaCommandOutput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        inputSetName.setEnabled(false);

        btnSetName.setText("Set Name");
        btnSetName.setEnabled(false);

        javax.swing.GroupLayout PanelToolsLayout = new javax.swing.GroupLayout(PanelTools);
        PanelTools.setLayout(PanelToolsLayout);
        PanelToolsLayout.setHorizontalGroup(
            PanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelToolsLayout.createSequentialGroup()
                        .addGroup(PanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(PanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputFileDir, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelToolsLayout.createSequentialGroup()
                                .addComponent(inputConvertedDir, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnSetConvertedDir))))
                    .addGroup(PanelToolsLayout.createSequentialGroup()
                        .addComponent(radioUseConverted)
                        .addGap(10, 10, 10)
                        .addComponent(BtnConvertToMjpeg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxSameAsSource)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSetName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSetName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(radioUseOriginal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelToolsLayout.setVerticalGroup(
            PanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelToolsLayout.createSequentialGroup()
                .addGroup(PanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputFileDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputConvertedDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSetConvertedDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConvertToMjpeg)
                    .addComponent(radioUseConverted)
                    .addComponent(checkBoxSameAsSource)
                    .addComponent(inputSetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(radioUseOriginal))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Mosaic Option")));

        jLabel3.setText("Map Name");

        jLabel4.setText("Video Name");

        BtnStartMosaicing.setText("Start Mosaicing");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputMapName)
                    .addComponent(inputVideoName, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnStartMosaicing, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputMapName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnStartMosaicing)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputVideoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        MenuFile.setText("File");

        MenuOpenFile.setText("Open File");
        MenuFile.add(MenuOpenFile);

        MenuBar.add(MenuFile);

        jMenu2.setText("Edit");
        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PanelTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxSameAsSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSameAsSourceActionPerformed
        // TODO add your handling code here:
        checkSameAsSource();
    }//GEN-LAST:event_checkBoxSameAsSourceActionPerformed

    private void radioUseOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUseOriginalActionPerformed
        // TODO add your handling code here:
        if(radioUseOriginal.isSelected()){
            BtnConvertToMjpeg.setEnabled(false);
            checkBoxSameAsSource.setEnabled(false);
            //BtnSetConvertedDir.setEnabled(false);
            checkSameAsSource();
        }
    }//GEN-LAST:event_radioUseOriginalActionPerformed

    private void radioUseConvertedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUseConvertedActionPerformed
        // TODO add your handling code here:
        if(radioUseConverted.isSelected()){
            BtnConvertToMjpeg.setEnabled(true);
            checkBoxSameAsSource.setEnabled(true);
            //BtnSetConvertedDir.setEnabled(true);
            checkSameAsSource();
        }
    }//GEN-LAST:event_radioUseConvertedActionPerformed
    //Listener
    
    public void addOpenFileListener(ActionListener openFileListener){
        MenuOpenFile.addActionListener(openFileListener);
    }
    public void addConvertedButtonListener(ActionListener convertedButtonListener){
        BtnConvertToMjpeg.addActionListener(convertedButtonListener);
    }
    public void addConvertDirectoryListener(ActionListener convertDir){
        BtnSetConvertedDir.addActionListener(convertDir);
    }
    public void addSetNameListener(ActionListener setFileNameButtonListener){
        btnSetName.addActionListener(setFileNameButtonListener);
    }
    public void addMosaicButtonListener(ActionListener MosaicButton){
        BtnStartMosaicing.addActionListener(MosaicButton);
    }
    private void checkSameAsSource(){
        if(radioUseConverted.isSelected()){
            if(checkBoxSameAsSource.isSelected()){            
                this.BtnSetConvertedDir.setEnabled(false);
                this.inputSetName.setEnabled(true);
                this.btnSetName.setEnabled(true);
            }else{            
                this.BtnSetConvertedDir.setEnabled(true);
                this.inputSetName.setEnabled(false);
                this.btnSetName.setEnabled(false);
            }
            
        }else{
            this.inputSetName.setEnabled(false);
            this.btnSetName.setEnabled(false);
            this.BtnSetConvertedDir.setEnabled(false);
        }
    }
    //End Listener
    public void setMapName(String filename){
        this.inputMapName.setText(filename);
    }
    public String getMapName(){
        return this.inputMapName.getText();
    }
    public void setVideoName(String filename){
        this.inputVideoName.setText(filename);
    }
    public String getVideoName(){
        return this.inputVideoName.getText();
    }
    public String getSetName(){
       return this.inputSetName.getText();
    }
    public void displayError(String error){
        JOptionPane.showMessageDialog(this, error);
    }
    public void setFileDir(String fileDir){
        
        this.inputFileDir.setText(fileDir);
    }
    public String getFileDir(){                 
        return this.inputFileDir.getText();
    }
    public void setConvertedFileDir(String converted){        
        this.inputConvertedDir.setText(converted);
    }
    public String getConvertedFileDir(){        
        return this.inputConvertedDir.getText();
    }
    public boolean checkUseConverted(){
        if(this.radioUseConverted.isSelected()){
            return true;
        }else{
            return false;
        }
    }
    public void setCommandOutput(String output){
        //TextAreaCommandOutput.setText(output);
        TextAreaCommandOutput.append(output);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConvertToMjpeg;
    private javax.swing.JButton BtnSetConvertedDir;
    private javax.swing.JButton BtnStartMosaicing;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuOpenFile;
    private javax.swing.JPanel PanelTools;
    private javax.swing.ButtonGroup RadionButtonGroup;
    private javax.swing.JTextArea TextAreaCommandOutput;
    private javax.swing.JButton btnSetName;
    private javax.swing.JCheckBox checkBoxSameAsSource;
    private javax.swing.JTextField inputConvertedDir;
    private javax.swing.JTextField inputFileDir;
    private javax.swing.JTextField inputMapName;
    private javax.swing.JTextField inputSetName;
    private javax.swing.JTextField inputVideoName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioUseConverted;
    private javax.swing.JRadioButton radioUseOriginal;
    // End of variables declaration//GEN-END:variables
}
